# Generated by Django 3.2.4 on 2021-07-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children_garden',
            old_name='popularity',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='children_garden',
            name='average_chek',
        ),
        migrations.RemoveField(
            model_name='children_garden',
            name='feedbacks',
        ),
    ]
