# Generated by Django 3.2.4 on 2021-07-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210703_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murshrut', models.CharField(max_length=200)),
                ('murshrut_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('start_work', models.TimeField()),
                ('stop_work', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('option', models.CharField(max_length=200)),
                ('average_price', models.IntegerField()),
                ('start_work', models.TimeField()),
                ('stop_work', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trolleibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murshrut', models.CharField(max_length=200)),
                ('murshrut_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('start_work', models.TimeField()),
                ('stop_work', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='educator',
            name='children_garden',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Children_Garden',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
